# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  repoName: 'janzi/vsts-build-agents'
  tagName: 'ubuntu-$(ubuntuversion)'
  tagNamest: 'ubuntu-$(ubuntuversion)-standard'
  tagNamestb: 'ubuntu-$(ubuntuversion)-standard-buildah'
  tagNamedst: 'ubuntu-$(ubuntuversion)-docker-standard'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  displayName: Build base image
  inputs:
    command: 'build'
    repository: '$(repoName)'
    Dockerfile: 'ubuntu/$(ubuntuversion)/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(tagName)
    addPipelineData: true
    arguments: -t $(repoName):$(tagName)

- task: Docker@2
  displayName: Build standard image
  inputs:
    command: 'build'
    repository: '$(repoName)'
    Dockerfile: 'ubuntu/$(ubuntuversion)/standard/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(tagNamest)
    addPipelineData: true
    arguments: -t $(repoName):$(tagNamest)

- task: Docker@2
  displayName: Build standard with buildah image
  condition: and(succeeded(), eq(variables['supportBuildah'], 'true'))
  inputs:
    command: 'build'
    repository: '$(repoName)'
    Dockerfile: 'ubuntu/$(ubuntuversion)/buildah/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(tagNamestb)
    addPipelineData: true
    arguments: -t $(repoName):$(tagNamestb)

- task: Docker@2
  displayName: Build docker standard image
  inputs:
    command: 'build'
    repository: '$(repoName)'
    Dockerfile: 'ubuntu/$(ubuntuversion)/docker/18.06.3-ce/standard/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(tagNamedst)
    addPipelineData: true
    arguments: -t $(repoName):$(tagNamedst)

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub

- task: Docker@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
    repository: '$(repoName)'
    includeSourceTags: true
    addDefaultLabels: true
    imageName: $(repoName):$(tagName)
    command: 'push'

- task: Docker@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
    repository: '$(repoName)'
    includeSourceTags: true
    addDefaultLabels: true
    imageName: $(repoName):$(tagNamedst)
    command: 'push'

- task: Docker@1
  condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['supportBuildah'], 'true')))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
    repository: '$(repoName)'
    includeSourceTags: true
    addDefaultLabels: true
    imageName: $(repoName):$(tagNamestb)
    command: 'push'


- task: Docker@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
    repository: '$(repoName)'
    includeSourceTags: true
    addDefaultLabels: true
    imageName: $(repoName):$(tagNamest)
    command: 'push'

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: dockerhub

